name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    # We run the tests 20 times because sometimes it helps highlight flaky
    # behaviors that do not trigger on a single pass.
    - name: Go Tests
      run: make test count=20

  golangci-lint:
    name: Go Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          check-latest: true
      - run: go mod download
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.0
          args: --timeout 5m --issues-exit-code 0 # warn only

  wasi-test:
    name: WASI Test Suite
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        check-latest: true

    - name: WASI Tests
      run: make wasi-testsuite
