name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true

    - name: Go Tests
      run: make test

  WASI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        check-latest: true

    - name: WASI Tests
      run: make wasi-testsuite
